{
 "title": "aquacultura",
 "time": { "from": "2002-01-01T00:00:00.000Z", "to": "2023-01-01T23:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "jaula",
    "label": "Jaula",
    "query": "SELECT * FROM aquacultura.dbo.personal_jaula"
   },
   {
    "name": "tabelas",
    "label": "tabelas",
    "query": "movimento,temperatura,desova,dados,jaula,data,vacina"
   },
   {
    "name": "variavel",
    "label": "variavel",
    "query": "SELECT name FROM sys.columns WHERE object_id = OBJECT_ID('dbo.personal_$tabelas')  "
   }
  ]
 },
 "panels": [
  {
   "title": "Tabela geral",
   "type": "table",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT ${variavel:csv} FROM aquacultura.dbo.personal_$tabelas"
    }
   ]
  },
  {
   "title": "Alimentacao",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT id_jaula_id as 'Jaula', temp as 'Temperatura',peso_inicio as 'Peso incial',peso_fim  as 'Peso final',valor as 'Valor' \r\nfrom aquacultura.dbo.personal_alimentacao \r\nwhere id_jaula_id in ($jaula)"
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "aquacultura",
     "rawSql": "SELECT data_id,temperatura FROM aquacultura.dbo.personal_temperatura"
    },
    { "dataset": "aquacultura" }
   ]
  },
  {
   "title": "Fator de crescimento",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "dataset": "aquacultura",
     "rawSql": "SELECT\r\n  FC_real as 'Fator de crescimento',\r\n  FC as 'Fator de crescimento(Teórico)',\r\n  data_id\r\nFROM\r\n  aquacultura.dbo.personal_dados\r\nWHERE \r\n  id_jaula_id IN ($jaula) "
    }
   ]
  },
  {
   "title": "Percentagem de alimentação",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dataset": "aquacultura",
     "rawSql": "SELECT\r\n  percentagem_alimentacao as 'Percentagem de alimentação',\r\n  data_id\r\nFROM\r\n  aquacultura.dbo.personal_dados\r\nWHERE \r\n  id_jaula_id IN ($jaula) "
    }
   ]
  },
  {
   "title": "Peixes mortos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "dataset": "aquacultura",
     "rawSql": "SELECT\r\n  num_mortos_real as 'Peixes mortos',\r\n  num_mortos_teorico as \"Peixes mortos(Teórico)\",\r\n  data_id\r\nFROM\r\n  aquacultura.dbo.personal_dados\r\nWHERE \r\n  id_jaula_id IN ($jaula) "
    }
   ]
  },
  {
   "title": "Tabelas de desovas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "dataset": "aquacultura",
     "rawSql": "SELECT\r\n  data_id,embrionados as 'Embrionados'\r\nFROM\r\n  aquacultura.dbo.personal_desova "
    },
    {
     "rawSql": "SELECT\r\n  femeas as 'Fêmeas',desovados as 'Desovados',data_id\r\nFROM\r\n  aquacultura.dbo.personal_desova "
    }
   ]
  },
  {
   "title": "Vacinas",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "rawSql": "SELECT * FROM aquacultura.dbo.personal_vacina where id_jaula_id IN ($jaula)"
    }
   ]
  },
  {
   "title": "Movimentos",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "rawSql": "SELECT data_id as data,num as numero, jaula_inicio_id as \"jaula inicio\", jaula_fim_id as \"jaula fim\" FROM aquacultura.dbo.personal_movimento WHERE (jaula_fim_id IN ($jaula) OR jaula_inicio_id IN ($jaula))"
    }
   ]
  },
  {
   "title": "Venda",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "targets": [
    {
     "rawSql": "select data_id as data, PM, id_jaula_id as jaula from aquacultura.dbo.personal_dados where PM >0.2"
    }
   ]
  },
  {
   "title": "Vender no ano seguinte",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
   "targets": [
    {
     "rawSql": "select data_id as data, PM, id_jaula_id as jaula from aquacultura.dbo.personal_dados where PM <0.2 AND PM >0.02"
    }
   ]
  },
  {
   "title": "Vendas",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
   "targets": [
    {
     "rawSql": "select num as numero, data_id as data from aquacultura.dbo.personal_movimento where venda = 1"
    }
   ]
  }
 ]
}