{
 "title": "aquacultura",
 "time": { "from": "2002-01-01T00:00:00.000Z", "to": "2023-01-01T23:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "tabelas",
    "label": "tabelas",
    "query": "movimento,temperatura,desova,dados,jaula,data,vacina"
   },
   {
    "name": "variavel",
    "label": "variavel",
    "query": "SELECT name FROM sys.columns WHERE object_id = OBJECT_ID('dbo.personal_$tabelas')  "
   },
   {
    "name": "jaula",
    "label": "Jaula",
    "query": "SELECT * FROM aquacultura.dbo.personal_jaula"
   }
  ]
 },
 "panels": [
  {
   "title": "imagem",
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tabela da jaula",
   "type": "table",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT ${variavel:csv} FROM aquacultura.dbo.personal_$tabelas"
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "aquacultura",
     "rawSql": "SELECT data_id,temperatura FROM aquacultura.dbo.personal_temperatura"
    }
   ]
  },
  {
   "title": "Fator de crescimento",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "dataset": "aquacultura",
     "rawSql": "SELECT\r\n  FC as 'Fator de crescimento',\r\n  data_id\r\nFROM\r\n  aquacultura.dbo.personal_dados\r\nWHERE \r\n  id_jaula_id IN ($jaula) "
    }
   ]
  },
  {
   "title": "Percentagem de alimentação",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dataset": "aquacultura",
     "rawSql": "SELECT\r\n  percentagem_alimentacao as 'Percentagem de alimentação',\r\n  data_id\r\nFROM\r\n  aquacultura.dbo.personal_dados\r\nWHERE \r\n  id_jaula_id IN ($jaula) "
    }
   ]
  },
  {
   "title": "Peixes mortos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "dataset": "aquacultura",
     "rawSql": "SELECT\r\n  num_mortos_real as 'Peixes mortos',\r\n  data_id\r\nFROM\r\n  aquacultura.dbo.personal_dados\r\nWHERE \r\n  id_jaula_id IN ($jaula) "
    }
   ]
  },
  {
   "title": "Tabelas de desovas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "dataset": "aquacultura",
     "rawSql": "SELECT\r\n  data_id,embrionados as 'Embrionados'\r\nFROM\r\n  aquacultura.dbo.personal_desova "
    },
    {
     "rawSql": "SELECT\r\n  femeas as 'Fêmeas',desovados as 'Desovados',data_id\r\nFROM\r\n  aquacultura.dbo.personal_desova "
    }
   ]
  }
 ]
}