# Generated by Django 4.1.3 on 2023-02-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desova',
            fields=[
                ('data', models.DateField(default=None, primary_key=True, serialize=False)),
                ('femeas', models.IntegerField(default=None)),
                ('desovados', models.IntegerField(default=None)),
                ('embrionados', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Jaula',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=None)),
                ('num_peixes', models.PositiveIntegerField(default=None)),
                ('data', models.DateField(primary_key=True, serialize=False)),
                ('PM', models.FloatField(default=None)),
                ('Biom', models.FloatField(default=None)),
                ('percentagem_alimentacao', models.FloatField(default=None)),
                ('peso', models.FloatField(default=None)),
                ('sacos_racao', models.FloatField(default=None)),
                ('FC', models.FloatField(default=None)),
                ('peso_medio', models.FloatField(default=None)),
                ('PM_teorica_alim_real', models.FloatField(default=None)),
                ('alimentacao_real', models.FloatField(default=None)),
                ('PM_teorico', models.FloatField(default=None)),
                ('PM_real', models.FloatField(default=None)),
                ('percentagem_mortalidade_teorica', models.FloatField(default=None)),
                ('num_mortos_teorico', models.FloatField(default=None)),
                ('percentagem_mortalidade_real', models.FloatField(default=None)),
                ('num_mortos_real', models.FloatField(default=None)),
                ('retirados', models.PositiveSmallIntegerField(default=None)),
                ('colocados', models.PositiveSmallIntegerField(default=None)),
                ('FC_real', models.FloatField(default=None)),
                ('volume', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('data', models.DateField(primary_key=True, serialize=False)),
                ('temperatura', models.FloatField(default=None)),
            ],
        ),
    ]
