# Generated by Django 4.1.4 on 2023-03-08 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('data', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Jaula',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=None, primary_key=True, serialize=False)),
                ('massa_volumica', models.FloatField(default=None)),
                ('volume', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='personal.data')),
                ('num_peixes', models.PositiveIntegerField(default=None)),
                ('PM', models.FloatField(default=None)),
                ('Biom', models.FloatField(default=None)),
                ('percentagem_alimentacao', models.FloatField(default=None)),
                ('peso', models.FloatField(default=None)),
                ('sacos_racao', models.FloatField(default=None)),
                ('FC', models.FloatField(default=None)),
                ('PM_teorica_alim_real', models.FloatField(default=None)),
                ('alimentacao_real', models.FloatField(default=None)),
                ('PM_teorico', models.FloatField(default=None)),
                ('PM_real', models.FloatField(default=None)),
                ('percentagem_mortalidade_teorica', models.FloatField(default=None)),
                ('num_mortos_teorico', models.FloatField(default=None)),
                ('percentagem_mortalidade_real', models.FloatField(default=None)),
                ('num_mortos_real', models.FloatField(default=None)),
                ('peso_medio', models.FloatField(default=None)),
                ('FC_real', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Desova',
            fields=[
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='personal.data')),
                ('femeas', models.IntegerField(default=None)),
                ('desovados', models.IntegerField(default=None)),
                ('embrionados', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('temperatura', models.FloatField(default=None)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='personal.data')),
            ],
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=None)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.data')),
                ('jaula_fim', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_fim', to='personal.jaula')),
                ('jaula_inicio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_inicio', to='personal.jaula')),
            ],
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='personal.data')),
                ('num', models.IntegerField(default=None)),
                ('PM', models.FloatField(default=None)),
                ('id_jaula', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='personal.jaula')),
            ],
        ),
        migrations.AddConstraint(
            model_name='movimento',
            constraint=models.UniqueConstraint(fields=('data', 'jaula_inicio', 'jaula_fim'), name='my_model_pk'),
        ),
        migrations.AddField(
            model_name='dados',
            name='id_jaula',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='personal.jaula'),
        ),
    ]
