# Generated by Django 4.1.4 on 2023-05-24 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentacaoFc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('valor', models.FloatField(default=None)),
                ('peso_inicio', models.FloatField()),
                ('peso_fim', models.FloatField()),
                ('temp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CalculosTemperatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(default=None)),
                ('ano', models.IntegerField(default=None)),
                ('media', models.FloatField(default=None)),
                ('minimo', models.FloatField(default=None)),
                ('maximo', models.FloatField(default=None)),
                ('soma', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('data', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Jaula',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=None, primary_key=True, serialize=False)),
                ('massa_volumica', models.FloatField(default=None)),
                ('volume', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Desova',
            fields=[
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='personal.data')),
                ('femeas', models.IntegerField(default=None)),
                ('desovados', models.IntegerField(default=None)),
                ('embrionados', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('temperatura', models.FloatField(default=None)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='personal.data')),
            ],
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='personal.data')),
                ('num', models.IntegerField(default=None)),
                ('PM', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=None)),
                ('PM', models.FloatField(default=None)),
                ('venda', models.BooleanField(default=False)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.data')),
                ('jaula_fim', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_fim', to='personal.jaula')),
                ('jaula_inicio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_inicio', to='personal.jaula')),
            ],
        ),
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_peixes', models.PositiveIntegerField(default=None)),
                ('PM', models.FloatField(default=None)),
                ('Biom', models.FloatField(default=None)),
                ('percentagem_alimentacao', models.FloatField(default=None)),
                ('peso', models.FloatField(default=None)),
                ('sacos_racao', models.FloatField(default=None)),
                ('FC', models.FloatField(default=None)),
                ('PM_teorica_alim_real', models.FloatField(default=None)),
                ('alimentacao_real', models.FloatField(default=None)),
                ('PM_teorico', models.FloatField(default=None)),
                ('PM_real', models.FloatField(default=None)),
                ('percentagem_mortalidade_teorica', models.FloatField(default=None)),
                ('num_mortos_teorico', models.FloatField(default=None)),
                ('percentagem_mortalidade_real', models.FloatField(default=None)),
                ('num_mortos_real', models.FloatField(default=None)),
                ('peso_medio', models.FloatField(default=None)),
                ('FC_real', models.FloatField(default=None)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.data')),
                ('id_jaula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.jaula')),
            ],
        ),
        migrations.AddConstraint(
            model_name='calculostemperatura',
            constraint=models.UniqueConstraint(fields=('ano', 'mes'), name='CalculosTemperatura_pk'),
        ),
        migrations.AddField(
            model_name='vacina',
            name='id_jaula',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='personal.jaula'),
        ),
    ]
